# General configuration parameters
log_file: "rufus.log"
log_level: "INFO"

# Crawling Configuration
max_depth: 1
delay: 20
do_rank: True
structured_output: True
timeout: 60
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"

# LLM Configuration for search query generation
llm_api_key: "AIzaSyAfn-WV-ZhcpT-GwpRY6J-FyQcMn5zlT14"
llm_provider: "google"
llm_name: "models/gemini-1.5-flash-latest"

# Embedding Model (Ranker) Configuration
embd_model_api_key: "AIzaSyAfn-WV-ZhcpT-GwpRY6J-FyQcMn5zlT14"
embd_model_provider: "google"
embd_model_name: "models/text-embedding-004"

# Ranker Similarity Metric Configuration
similarity_metric: "cosine"

# Search Engine
search_engine: "google"
num_search_results: 10
